workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - name: Give execution permission
        script: | 
          chmod +x gradlew
      - name: Fix Package Name and Imports
        script: |
          # هذا الأمر يبحث عن أي نص قديم ويستبدله بالجديد في كل ملفات الجافا
          find . -type f -name "*.java" -print0 | xargs -0 sed -i '' 's/sngine\.app\.webview/shofyou\.app\.webview/g'
          find . -type f -name "AndroidManifest.xml" -print0 | xargs -0 sed -i '' 's/sngine\.app\.webview/shofyou\.app\.webview/g'
      - name: Build Android App
        script: | 
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
