workflows:
  android-workflow:
    name: Final Auto-Fix Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - name: Give execution permission
        script: chmod +x gradlew
      - name: Auto-Fix Imports and Package
        script: |
          # هذا السطر يبحث عن أي كلمة sngine.app.webview ويحولها لـ com.shofyou.app.webview في كل الملفات
          find . -type f \( -name "*.java" -o -name "AndroidManifest.xml" \) -print0 | xargs -0 sed -i '' 's/sngine\.app\.webview/com\.shofyou\.app\.webview/g'
      - name: Build Android App
        script: | 
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
